import random 
start = input("what you want? : ")
if start == "joke" or "jokes":
    a =["Programmer: A machine that turns coffee into code.",
            "Computers are fast; programmers keep it slow",
            "When I wrote this code, only God and I understood what I did. Now only God knows",
            "A son asked his father (a programmer) why the sun rises in the east, and sets in the west. His response? It works, don’t touch!",
            "How many programmers does it take to change a light bulb? None, that’s a hardware problem",
            "Programming is like sex: One mistake and you have to support it for the rest of your life.",
            "Programming can be fun, and so can cryptography; however, they should not be combined.",
            "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.",
            "Copy-and-Paste was programmed by programmers for programmers actually.",
            "Always code as if the person who ends up maintaining your code will be a violent psychopath who knows where you live.",
            "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.",
            "Algorithm: Word used by programmers when they don’t want to explain what they did.",
            "Software and cathedrals are much the same — first we build them, then we pray.",
            "There are two ways to write error-free programs; only the third works.",
            "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
            "99 little bugs in the code. 99 little bugs in the code. Take one down, patch it around. 127 little bugs in the code …",
            "Remember that there is no code faster than no code.",
            "One man’s crappy software is another man’s full-time job.",
            "No code has zero defects.",
            "A good programmer is someone who always looks both ways before crossing a one-way street.",
            "Deleted code is debugged code.",
            "Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.",
            "It’s not a bug — it’s an undocumented feature.Voodoo Programming",
            "It works on my machine.",
            "It compiles; ship it.",
            "I have not failed. I’ve just found 10,000 ways that won’t work.",
            "I have always wished that my computer would be as easy to use as my telephone. My wish has come true. I no longer know how to use my telephone.",
            "When we had no computers, we had no programming problems either.",
            "There is an easy way and a hard way. The hard part is finding the easy way.",
            "Computers are good at following instructions but not at reading your mind.",
            "The best way to get accurate information on Usenet is to post something wrong and wait for corrections.",
            "The computer was born to solve problems that did not exist before.",
            "Q: Is the glass half-full or half-empty? A: The glass is twice as big as it needs to be.",
            "In theory, there ought to be no difference between theory and practice. In practice, there is.",
            "There is no Ctrl-Z in life.",
            "Whitespace is never white.",
            "When all else fails … reboot.",
            "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
            "In a room full of top software designers, if two agree on the same thing, that’s a majority.",
            "One: Demonstrations always crash. And two: The probability of them crashing goes up exponentially with the number of people watching.",
            "A program is never less than 90% complete and never more than 95% complete.",
            "In a software project team of ten, there are probably three people who produce enough defects to make them net-negative producers.",
            "Most of you are familiar with the virtues of a programmer. There are three, of course: laziness, impatience, and hubris.",
            "I’ve finally learned what upward compatible means. It means we get to keep all our old mistakes.",
            "Walking on water and developing software from a specification are easy if both are frozen.",
            "Documentation is like sex: When it is bad, it is better than nothing. When it is good, it is really, really good.",
            "Software undergoes beta testing shortly before it’s released. Beta is Latin for still doesn’t work.",
            "UNIX is simple. It just takes a genius to understand its simplicity.",
            "There’s no place like 127.0.0.1.",
            "Hardware is made to last. Software is made to change. Change is the only thing that lasts. Software wins.",
            "ASCII stupid question, get a stupid ANSI.",
            ".NET is called .NET so that it wouldn’t show up in a UNIX directory listing.",
            "vi vi vi — the editor of the beast.",
            "If the box says, ‘This software requires Windows XP or better,’ does that mean it’ll run on Linux?",
            "Keyboard Failure. Press F1 to continue.",
            "Potential partners are like internet domain names — the ones I like are already taken.",
            "A system administrator has two problems: 1. Dumb users. 2. Smart users.",
            "Linux is only free if your time has no value.",
            "Why programmers like UNIX: unzip, strip, touch, finger, grep, mount, fsck, more, yes, fsck, fsck, fsck, umount, sleep.",
            "UNIX is user friendly. It’s just very particular about who its friends are.",
            "UNIX was not designed to stop people from doing stupid things, because that would also stop them from doing clever things."]
    b = random.choice(a)
    print(b)
else:
    print("hey dude my job is to tell joke nothing else ok so let me do that only ok 😁")